[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#8f420eff"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
red = "#F92672"
green = "#A6E22E"
yellow = "#F4BF75"
blue = "#E66100"
magenta = "#AE81FF"
cyan = "#A1EFE4"
white = "#F8F8F2"



[colors.primary]
background = "#000000"
foreground = "#00A600"

[font]
size = 14.0

[font.bold]
family = "terminus"
style = "Bold"

[font.bold_italic]
family = "terminus"
style = "Bold Italic"

[font.italic]
family = "terminus"
style = "Italic"

[font.normal]
family = "terminus"
style = "Bold"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 50000

[window]
opacity = 1
